DROP TABLE if EXISTS animal;
CREATE TABLE if not exists animal(
`id` INT NOT NULL AUTO_INCREMENT,
`name` VARCHAR(50) DEFAULT NULL,
`age` INT DEFAULT NULL,
`kind` VARCHAR(50) DEFAULT NULL,
`phone` VARCHAR(50) DEFAULT NULL,
`owner` VARCHAR(50) DEFAULT NULL,
`image_url` VARCHAR(50) DEFAULT NULL,
`animal_code` VARCHAR(255) NOT NULL UNIQUE,
PRIMARY KEY(`id`)
);